//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuSolver2010 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuSolver2010.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH0ABZV500CJ40S0Q800001GNE0000000MP080V47C0WA0F0+M0500Q0KJNX0B003P0D0000J0ISQN0H08O06FU900000T0L1G0+025VB0E00002000PS0013VJDX000E000FIO0H0U46GC7E000600GIMB0000H009F+7C2TJD0YVSQ1K8010000FX60U90E0PG0NDI0VMA7C04000R3+TJAWLV03Z09T00080Q00R00D00C0UHNJ000Y0O0I0X00GL01PS9DV02O600W8T0F00E+000AQH08000DI0C4U010TAHM00XO00V002L6J3E5GKM00U002EV0X70G000J00IC00S1W8DA+0LNZF02Y64508OWK0F+0ENC00BS0U00000I009T71PQ0E0100JN03Z4XUI620Y5G000007000DS00D600+0OJ000R7PB18H0000QE0Z0UF5004VMC00S0008YQPTK0L06O00G00JND0270HFE00+UYPJ5EOB0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigPuzzles36X36 {
            get {
                return ResourceManager.GetString("BigPuzzles36X36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000942080160000029000000008906000001400250000004000000020008090050000700
        ///094000130000000000000076002080010000032000000000200060000050400000008007006304008
        ///000007000090001000000045006000020000036000410500000809000000004000018000081500032
        ///052470000060000000000008010400000009700950000020040030000800090000003706000091000
        ///090000000001006000060080070300000010000039000000050002170400028000003000086000057
        ///000005000020004010030080020000008400800600000090010705006000000950003060003000001
        ///50006800000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyPuzzles {
            get {
                return ResourceManager.GetString("EasyPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 44 0 30 19 37 0 0 0 0 10 14 55 54 0 0 32 0 31 0 0 0 0 58 27 24 26 52 0 57 0 48 0 8 47 0 15 18 7 33 6 0 51 45 0 0 16 64 0 12 20 0 0 1 22 0 0 13 49 0 5 0 0 61
        ///0 61 58 5 51 0 32 11 0 16 0 0 25 0 6 0 50 0 52 0 62 40 57 54 47 8 22 0 0 0 60 34 44 0 38 3 0 0 39 0 9 23 53 37 14 29 0 35 0 0 55 59 0 19 4 13 0 0 10 27 0 2 17 0
        ///0 49 55 21 0 23 0 60 0 62 41 0 33 0 0 35 9 0 64 0 56 0 0 0 0 0 0 0 32 42 4 0 51 36 48 25 24 0 0 0 0 0 34 52 0 3 0 18 0 0 0 0 53 0 0 38 11 22 39 40 37 0 0 30
        ///0 8 0 56 39 0 45 38 47 0 20 0 53 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enormous {
            get {
                return ResourceManager.GetString("Enormous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000000900970300000010060500004708002000002006031004000000800167087000000
        ///000000000000005308900308002009000507050002000070000690080000040000043005402000800
        ///000000000000300060800100342002030078006900000000008050200009007170000000000600030
        ///000000000000301400062040350019600000000073200000100006000050089400000500008007000
        ///000000000004005000063001070015003208009000000000600400040000090307040002500900700
        ///000000000005090170030002008400000000009400300070860004007008000200000001001900056
        ///00000000000609 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hard2365 {
            get {
                return ResourceManager.GetString("Hard2365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400000805030000000000700000020000060000080400000010000000603070500200000104000000
        ///520006000000000701300000000000400800600000050000000000041800000000030020008700000
        ///600000803040700000000000000000504070300200000106000000020000050000080600000010000
        ///480300000000000071020000000705000060000200800000000000001076000300000400000050000
        ///000014000030000200070000000000900030601000000000000080200000104000050600000708000
        ///000000520080400000030009000501000600200700000000300000600010000000000704000000030
        ///60205000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hard95 {
            get {
                return ResourceManager.GetString("Hard95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 520006000000000701300000000000400800600000050000000000041800000000030020008700000
        ///400000805030000000000700000020000060000080400000010000000603070500200000104000000
        ///480300000000000071020000000705000060000200800000000000001076000300000400000050000
        ///600000803040700000000000000000504070300200000106000000020000050000080600000010000
        ///040700060003900000000000057000000030200080000019000570600040000050100000020006084
        ///000000520080400000030009000501000600200700000000300000600010000000000704000000030
        ///07000930000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HardPuzzles {
            get {
                return ResourceManager.GetString("HardPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000000008507010020000000000030006000009005230060003010001800054040690007
        ///000000000000000010500030200007000000003050620400168507008001000039026080000070006
        ///000000000000000024600308070000000000005020098308500240000003000007046000906007801
        ///000000000000000036102800000075040000000001940004500200040003060060702000000100500
        ///000000000000000070034090021003040000097800000010000380000001030060500004800603507
        ///000000000000000127009002530000000000004000981080754000000000000060089003473105000
        ///00000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VeryLargeSet {
            get {
                return ResourceManager.GetString("VeryLargeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///000003700520000000830000000360850000000000390000340000400030085003007000000100000
        ///00000370052000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorldsHardest {
            get {
                return ResourceManager.GetString("WorldsHardest", resourceCulture);
            }
        }
    }
}
